# Generated by Django 5.1.3 on 2024-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_applicationuser_checkme'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='socialMediaLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
